[package]
name = "librehub-security"
version.workspace = true
edition.workspace = true

[dependencies]
tempfile = "3"
librehub-common.workspace = true
librehub-publisher.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
getrandom = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
