[package]
name = "librehub-api"
version.workspace = true
edition.workspace = true
[dependencies]
librehub-supply-chain.workspace = true
librehub-common.workspace = true
librehub-validator.workspace = true
librehub-builder.workspace = true
librehub-publisher.workspace = true
librehub-source.workspace = true
librehub-catalog.workspace = true
librehub-security.workspace = true
base64 = "0.22"
url = "2"
sha2 = "0.10"
hmac = "0.12"
subtle = "2"
getrandom = "0.4"
chacha20poly1305 = "0.10"
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
fs2 = "0.4"
rusqlite = { version = "0.38", features = ["bundled"] }
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http = { version = "0.6", features = ["trace"] }
tracing.workspace = true
tracing-subscriber.workspace = true
tempfile = "3"
[dev-dependencies]
http-body-util = "0.1"
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
